In [27]:
import pandas as pd
url = "https://raw.githubusercontent.com/Talktodre-ops/techcrush-practice/refs/heads/main/insurance_claims.csv"
df = pd.read_csv(url)
df.head()
df.info()
df.describe()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           1000 non-null   int64
 1   age                          1000 non-null   int64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   object
 4   policy_state                 1000 non-null   object
 5   policy_csl                   1000 non-null   object
 6   policy_deductable            1000 non-null   int64
 7   policy_annual_premium        1000 non-null   float64
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   object
 11  insured_education_level      1000 non-null   object
 12  insured_occupation           1000 non-null   object
 13  insured_hobbies              1000 non-null   object
 14  insured_relationship         1000 non-null   object
 15  capital-gains                1000 non-null   int64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   object
 18  incident_type                1000 non-null   object
 19  collision_type               1000 non-null   object
 20  incident_severity            1000 non-null   object
 21  authorities_contacted        909 non-null    object
 22  incident_state               1000 non-null   object
 23  incident_city                1000 non-null   object
 24  incident_location            1000 non-null   object
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   object
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   object
 31  total_claim_amount           1000 non-null   int64
 32  injury_claim                 1000 non-null   int64
 33  property_claim               1000 non-null   int64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   object
 36  auto_model                   1000 non-null   object
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   object
 39  _c39                         0 non-null      float64
dtypes: float64(2), int64(17), object(21)
memory usage: 312.6+ KB

(1000, 40)

In [28]:
df.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,YES,71610,6510,13020,52080,Saab,92x,2004,Y,NaN
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,?,5070,780,780,3510,Mercedes,E400,2007,Y,NaN
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,NO,34650,7700,3850,23100,Dodge,RAM,2007,N,NaN
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y,NaN
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,NO,6500,1300,650,4550,Accura,RSX,2009,N,NaN

In [29]:
df.describe()

,months_as_customer,age,policy_number,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,capital-gains,capital-loss,incident_hour_of_the_day,number_of_vehicles_involved,bodily_injuries,witnesses,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_year,_c39
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,0.0
mean,203.954000,38.948000,546238.648000,1136.000000,1256.406150,1.101000e+06,501214.488000,25126.100000,-26793.700000,11.644000,1.83900,0.992000,1.487000,52761.94000,7433.420000,7399.570000,37928.950000,2005.103000,NaN
std,115.113174,9.140287,257063.005276,611.864673,244.167395,2.297407e+06,71701.610941,27872.187708,28104.096686,6.951373,1.01888,0.820127,1.111335,26401.53319,4880.951853,4824.726179,18886.252893,6.015861,NaN
min,0.000000,19.000000,100804.000000,500.000000,433.330000,-1.000000e+06,430104.000000,0.000000,-111100.000000,0.000000,1.00000,0.000000,0.000000,100.00000,0.000000,0.000000,70.000000,1995.000000,NaN
25%,115.750000,32.000000,335980.250000,500.000000,1089.607500,0.000000e+00,448404.500000,0.000000,-51500.000000,6.000000,1.00000,0.000000,1.000000,41812.50000,4295.000000,4445.000000,30292.500000,2000.000000,NaN
50%,199.500000,38.000000,533135.000000,1000.000000,1257.200000,0.000000e+00,466445.500000,0.000000,-23250.000000,12.000000,1.00000,1.000000,1.000000,58055.00000,6775.000000,6750.000000,42100.000000,2005.000000,NaN
75%,276.250000,44.000000,759099.750000,2000.000000,1415.695000,0.000000e+00,603251.000000,51025.000000,0.000000,17.000000,3.00000,2.000000,2.000000,70592.50000,11305.000000,10885.000000,50822.500000,2010.000000,NaN
max,479.000000,64.000000,999435.000000,2000.000000,2047.590000,1.000000e+07,620962.000000,100500.000000,0.000000,23.000000,4.00000,2.000000,3.000000,114920.00000,21450.000000,23670.000000,79560.000000,2015.000000,NaN

In [30]:
df.isnull().sum()
df.isnull().sum()/len(df)*100

months_as_customer               0.0
age                              0.0
policy_number                    0.0
policy_bind_date                 0.0
policy_state                     0.0
policy_csl                       0.0
policy_deductable                0.0
policy_annual_premium            0.0
umbrella_limit                   0.0
insured_zip                      0.0
insured_sex                      0.0
insured_education_level          0.0
insured_occupation               0.0
insured_hobbies                  0.0
insured_relationship             0.0
capital-gains                    0.0
capital-loss                     0.0
incident_date                    0.0
incident_type                    0.0
collision_type                   0.0
incident_severity                0.0
authorities_contacted            9.1
incident_state                   0.0
incident_city                    0.0
incident_location                0.0
incident_hour_of_the_day         0.0
number_of_vehicles_involved      0.0
property_damage                  0.0
bodily_injuries                  0.0
witnesses                        0.0
police_report_available          0.0
total_claim_amount               0.0
injury_claim                     0.0
property_claim                   0.0
vehicle_claim                    0.0
auto_make                        0.0
auto_model                       0.0
auto_year                        0.0
fraud_reported                   0.0
_c39                           100.0
dtype: float64

In [31]:
df['authorities_contacted'] = df['authorities_contacted'].fillna(df['authorities_contacted'].mode()[0])
df['policy_bind_date'] = pd.to_datetime(df['policy_bind_date'])
df['incident_date'] = pd.to_datetime(df['incident_date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           1000 non-null   int64
 1   age                          1000 non-null   int64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   datetime64[ns]
 4   policy_state                 1000 non-null   object
 5   policy_csl                   1000 non-null   object
 6   policy_deductable            1000 non-null   int64
 7   policy_annual_premium        1000 non-null   float64
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   object
 11  insured_education_level      1000 non-null   object
 12  insured_occupation           1000 non-null   object
 13  insured_hobbies              1000 non-null   object
 14  insured_relationship         1000 non-null   object
 15  capital-gains                1000 non-null   int64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   datetime64[ns]
 18  incident_type                1000 non-null   object
 19  collision_type               1000 non-null   object
 20  incident_severity            1000 non-null   object
 21  authorities_contacted        1000 non-null   object
 22  incident_state               1000 non-null   object
 23  incident_city                1000 non-null   object
 24  incident_location            1000 non-null   object
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   object
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   object
 31  total_claim_amount           1000 non-null   int64
 32  injury_claim                 1000 non-null   int64
 33  property_claim               1000 non-null   int64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   object
 36  auto_model                   1000 non-null   object
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   object
 39  _c39                         0 non-null      float64
dtypes: datetime64[ns](2), float64(2), int64(17), object(19)
memory usage: 312.6+ KB

In [32]:
df = df.drop(columns = ['_c39'])

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 39 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           1000 non-null   int64
 1   age                          1000 non-null   int64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   datetime64[ns]
 4   policy_state                 1000 non-null   object
 5   policy_csl                   1000 non-null   object
 6   policy_deductable            1000 non-null   int64
 7   policy_annual_premium        1000 non-null   float64
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   object
 11  insured_education_level      1000 non-null   object
 12  insured_occupation           1000 non-null   object
 13  insured_hobbies              1000 non-null   object
 14  insured_relationship         1000 non-null   object
 15  capital-gains                1000 non-null   int64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   datetime64[ns]
 18  incident_type                1000 non-null   object
 19  collision_type               1000 non-null   object
 20  incident_severity            1000 non-null   object
 21  authorities_contacted        1000 non-null   object
 22  incident_state               1000 non-null   object
 23  incident_city                1000 non-null   object
 24  incident_location            1000 non-null   object
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   object
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   object
 31  total_claim_amount           1000 non-null   int64
 32  injury_claim                 1000 non-null   int64
 33  property_claim               1000 non-null   int64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   object
 36  auto_model                   1000 non-null   object
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   object
dtypes: datetime64[ns](2), float64(1), int64(17), object(19)
memory usage: 304.8+ KB

In [34]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [35]:
df['fraud_reported'].value_counts()
df['fraud_reported'].value_counts(normalize=True)

fraud_reported
N    0.753
Y    0.247
Name: proportion, dtype: float64

In [36]:
from sklearn.utils import class_weight

In [37]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['fraud_reported'] = le.fit_transform(df['fraud_reported'])
df['fraud_reported'].value_counts()

fraud_reported
0    753
1    247
Name: count, dtype: int64

In [38]:
x = df.drop(columns =['fraud_reported'])
y =df['fraud_reported']

print(x.shape)
print(y.shape)

(1000, 38)
(1000,)

In [39]:
df_clean = x.drop(columns=['policy_number', 'policy_bind_date', 'incident_date', 'incident_location',])
print(df_clean.shape)

(1000, 34)

In [40]:
categorical_cols = df_clean.select_dtypes(include = 'object').columns.tolist()
numerical_cols = df_clean.select_dtypes(include = 'number').columns.tolist()

print(categorical_cols)
print(numerical_cols)

['policy_state', 'policy_csl', 'insured_sex', 'insured_education_level', 'insured_occupation', 'insured_hobbies', 'insured_relationship', 'incident_type', 'collision_type', 'incident_severity', 'authorities_contacted', 'incident_state', 'incident_city', 'property_damage', 'police_report_available', 'auto_make', 'auto_model']
['months_as_customer', 'age', 'policy_deductable', 'policy_annual_premium', 'umbrella_limit', 'insured_zip', 'capital-gains', 'capital-loss', 'incident_hour_of_the_day', 'number_of_vehicles_involved', 'bodily_injuries', 'witnesses', 'total_claim_amount', 'injury_claim', 'property_claim', 'vehicle_claim', 'auto_year']

In [41]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in categorical_cols:
  df_clean[col] = le.fit_transform(df_clean[col])
df_clean.head()

,months_as_customer,age,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,insured_sex,insured_education_level,...,bodily_injuries,witnesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year
0,328,48,2,1,1000,1406.91,0,466132,1,4,...,1,2,2,71610,6510,13020,52080,10,1,2004
1,228,42,1,1,2000,1197.22,5000000,468176,1,4,...,0,0,0,5070,780,780,3510,8,12,2007
2,134,29,2,0,2000,1413.14,5000000,430632,0,6,...,2,3,1,34650,7700,3850,23100,4,30,2007
3,256,41,0,1,2000,1415.74,6000000,608117,0,6,...,1,2,1,63400,6340,6340,50720,3,34,2014
4,228,44,0,2,1000,1583.91,6000000,610706,1,0,...,0,1,1,6500,1300,650,4550,0,31,2009

In [42]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_clean[numerical_cols] = scaler.fit_transform(df_clean[numerical_cols])
df_clean.head()

,months_as_customer,age,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,insured_sex,insured_education_level,...,bodily_injuries,witnesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year
0,1.078140,0.990836,2,1,-0.222383,0.616705,-0.479476,-0.489529,1,4,...,0.009759,0.461838,2,0.714257,-0.189283,1.165505,0.749653,10,1,-0.183440
1,0.208995,0.334073,1,1,1.412784,-0.242521,1.697980,-0.461008,1,4,...,-1.210174,-1.338700,0,-1.807312,-1.363822,-1.372696,-1.823346,8,12,0.315491
2,-0.608002,-1.088913,2,0,1.412784,0.642233,1.697980,-0.984885,0,6,...,1.229693,1.362107,1,-0.686362,0.054644,-0.736072,-0.785565,4,30,0.315491
3,0.452355,0.224613,0,1,1.412784,0.652886,2.133471,1.491682,0,6,...,0.009759,0.461838,1,0.403135,-0.224130,-0.219722,0.677607,3,34,1.479664
4,0.208995,0.552994,0,2,-0.222383,1.341980,2.133471,1.527808,1,0,...,-1.210174,-0.438431,1,-1.753121,-1.257232,-1.399654,-1.768252,0,31,0.648112

In [43]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df_clean, y, test_size=0.2, random_state=42)
print(x_train.shape)
print(x_test.shape)

(800, 34)
(200, 34)

In [44]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

model = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.92      0.83       145
           1       0.50      0.20      0.29        55

    accuracy                           0.72       200
   macro avg       0.63      0.56      0.56       200
weighted avg       0.68      0.72      0.68       200

0.725

In [45]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
x_train_smote, y_train_smote = smote.fit_resample(x_train, y_train)
model2 = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
model2.fit(x_train_smote, y_train_smote)
y_pred2 = model2.predict(x_test)
print(classification_report(y_test, y_pred2))
print(accuracy_score(y_test, y_pred2))

              precision    recall  f1-score   support

           0       0.81      0.88      0.84       145
           1       0.59      0.47      0.53        55

    accuracy                           0.77       200
   macro avg       0.70      0.67      0.68       200
weighted avg       0.75      0.77      0.76       200

0.765

In [46]:
model3 = RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42)
model3.fit(x_train_smote, y_train_smote)
y_pred3 = model3.predict(x_test)
print(classification_report(y_test, y_pred3))
print(accuracy_score(y_test, y_pred3))

              precision    recall  f1-score   support

           0       0.82      0.86      0.84       145
           1       0.56      0.49      0.52        55

    accuracy                           0.76       200
   macro avg       0.69      0.67      0.68       200
weighted avg       0.75      0.76      0.75       200

0.755

In [47]:
from xgboost import XGBClassifier

model4 = XGBClassifier(n_estimators=200, random_state=42, objective='binary:logistic')
model4.fit(x_train_smote, y_train_smote)
y_pred4 =model4.predict(x_test)
print(accuracy_score(y_test, y_pred4))
print(classification_report(y_test, y_pred4))

0.795
              precision    recall  f1-score   support

           0       0.85      0.87      0.86       145
           1       0.63      0.60      0.62        55

    accuracy                           0.80       200
   macro avg       0.74      0.73      0.74       200
weighted avg       0.79      0.80      0.79       200

In [49]:
from xgboost import XGBClassifier

model5 = XGBClassifier(n_estimators=300, max_depth=6, learning_rate=0.05, random_state=42, eval_metric='logloss')
model5.fit(x_train_smote, y_train_smote)
y_pred5 = model5.predict(x_test)
print(accuracy_score(y_test, y_pred5))
print(classification_report(y_test, y_pred5))

0.78
              precision    recall  f1-score   support

           0       0.85      0.85      0.85       145
           1       0.60      0.60      0.60        55

    accuracy                           0.78       200
   macro avg       0.72      0.72      0.72       200
weighted avg       0.78      0.78      0.78       200

In [52]:
y_prob = model4.predict_proba(x_test)[:, 1]
y_pred_threshold = (y_prob >=0.3).astype(int)
print(classification_report(y_test, y_pred_threshold))

              precision    recall  f1-score   support

           0       0.87      0.85      0.86       145
           1       0.62      0.65      0.64        55

    accuracy                           0.80       200
   macro avg       0.74      0.75      0.75       200
weighted avg       0.80      0.80      0.80       200

In [54]:
y_pred_threshold =(y_prob >=0.2).astype(int)
print(classification_report(y_test, y_pred_threshold))

              precision    recall  f1-score   support

           0       0.88      0.82      0.85       145
           1       0.60      0.71      0.65        55

    accuracy                           0.79       200
   macro avg       0.74      0.76      0.75       200
weighted avg       0.80      0.79      0.80       200

In [56]:
import joblib
joblib.dump(model4, 'fraud_detection_model.pkl')
print("Model saved!")

Model saved!

In [61]:
from google.colab import files
files.download('fraud_detection_model.pkl')